#!/bin/sh

PORT=libmatekbd

SCHEMAS=$(pkginfo -l ${PORT} | grep etc/mateconf/schemas/.*\.schemas\$)

for S in ${SCHEMAS}
do
	MATECONF_CONFIG_SOURCE="xml::/etc/mateconf/mateconf.xml.defaults" \
		mateconftool-2 --makefile-install-rule /${S}
done
